version: '3.7'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - queueapi
    volumes:
      - redis-data:/data
    command: ["redis-server"]

  db:
    image: kartoza/postgis:11.0-2.5
    environment:
      ALLOW_IP_RANGE: '0.0.0.0/0'
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DBNAME: queue-api-dev
    ports:
      - "5532:5432"
    networks:
      - queueapi
    volumes:
      - db-data:/var/lib/postgresql/data
      
  queue-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    depends_on: 
      - db
      - redis
    working_dir: /queueapi
    networks:
      - queueapi
    env_file:
      - env.conf
    volumes:
      - ./:/queueapi
    ports:
      - 8080:8080
    command: /queueapi/scripts/wait.sh db:5432 -- /bin/sh -c "yarn dev"

networks:
    queueapi:
      name: queueapi

volumes:
  db-data:
    driver: local
  redis-data: